username = str(input("Enter your username : "))
age = int(input("Enter your age : "))
stateOfOrigin = str(input("Enter your state of origin : "))
dateOfBirth = int(input("Enter your date of birth : "))
school = str(input("Enter your school : "))
department = str(input("Enter your department : "))
courseOfStudy = str(input("Enter your courseOfStudy : "))
print("Welcome " + username + " you are " + str(age) + "years old")
print("You are from " + stateOfOrigin + ", your year is " + str(dateOfBirth))
print("you school in " + school + "  you are in " + department + " you study " + courseOfStudy) 